#!/usr/bin/env node
/**
 * Copies vendor JS libraries and self-hosted font files from node_modules to public/.
 * Run: node scripts/vendor-copy.js
 * Called automatically via `npm run vendor:copy` (and as part of `npm run build`).
 */
import { cpSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const nm = join(root, 'node_modules');
const pub = join(root, 'public');

// ── JS vendor libraries ────────────────────────────────────────────────────────
const vendorDir = join(pub, 'vendor');
mkdirSync(vendorDir, { recursive: true });

const jsFiles = [
  ['alpinejs/dist/cdn.min.js', 'alpine.min.js'],
  ['@alpinejs/collapse/dist/cdn.min.js', 'alpine-collapse.min.js'],
  ['sortablejs/Sortable.min.js', 'sortable.min.js'],
  ['swagger-ui-dist/swagger-ui-bundle.js', 'swagger-ui-bundle.js'],
  ['swagger-ui-dist/swagger-ui.css', 'swagger-ui.css'],
  ['chart.js/dist/chart.umd.min.js', 'chart.min.js'],
  ['flatpickr/dist/flatpickr.min.js', 'flatpickr.min.js'],
  ['flatpickr/dist/flatpickr.min.css', 'flatpickr.min.css'],
];

for (const [src, dest] of jsFiles) {
  cpSync(join(nm, src), join(vendorDir, dest));
  console.log(`  vendor/${dest}`);
}

// ── Dexie (offline IndexedDB ORM) ──────────────────────────────────────────────
cpSync(join(nm, 'dexie/dist/modern/dexie.mjs'), join(vendorDir, 'dexie.mjs'));
console.log('  vendor/dexie.mjs');

// ── node-diff3 (server-side three-way merge) ───────────────────────────────────
// Vendored to public/ for the SW only — server uses the npm package directly.
try {
  cpSync(join(nm, 'node-diff3/dist/diff3.mjs'), join(vendorDir, 'node-diff3.mjs'));
  console.log('  vendor/node-diff3.mjs');
} catch {
  console.warn('  vendor/node-diff3.mjs — skipped (not found in node_modules)');
}

// ── Quill ──────────────────────────────────────────────────────────────────────
// Quill 2.x ships an unminified UMD bundle as `quill.js` (no `quill.min.js`).
const quillDir = join(vendorDir, 'quill');
mkdirSync(quillDir, { recursive: true });
cpSync(join(nm, 'quill/dist/quill.js'), join(quillDir, 'quill.js'));
cpSync(join(nm, 'quill/dist/quill.snow.css'), join(quillDir, 'quill.snow.css'));
console.log('  vendor/quill/quill.js + quill.snow.css');

// ── Konva (photo annotation, Phase T) ──────────────────────────────────────────
const konvaDir = join(vendorDir, 'konva');
mkdirSync(konvaDir, { recursive: true });
cpSync(join(nm, 'konva/konva.min.js'), join(konvaDir, 'konva.min.js'));
console.log('  vendor/konva/konva.min.js');

// ── FullCalendar ────────────────────────────────────────────────────────────────
const fcDir = join(vendorDir, 'fullcalendar');
mkdirSync(fcDir, { recursive: true });
const fcPackages = ['core', 'daygrid', 'timegrid', 'interaction'];
for (const pkg of fcPackages) {
  cpSync(
    join(nm, `@fullcalendar/${pkg}/index.global.min.js`),
    join(fcDir, `${pkg}.global.min.js`)
  );
  console.log(`  vendor/fullcalendar/${pkg}.global.min.js`);
}

// ── Fonts ───────────────────────────────────────────────────────────────────────
const fontsDir = join(pub, 'fonts');
mkdirSync(fontsDir, { recursive: true });

// Font families and the weights we actually use (latin subset only)
const fonts = [
  { pkg: '@fontsource/inter', weights: [300, 400, 500, 600, 700, 800], italic: false },
  { pkg: '@fontsource/dm-sans', weights: [300, 400, 500, 600, 700], italic: [400] },
  { pkg: '@fontsource/bricolage-grotesque', weights: [300, 400, 500, 600, 700, 800], italic: false },
  { pkg: '@fontsource/jetbrains-mono', weights: [400, 500, 600], italic: false },
  { pkg: '@fontsource/fraunces', weights: [600, 700], italic: false },
  { pkg: '@fontsource/instrument-serif', weights: [400], italic: [400] },
  { pkg: '@fontsource/source-serif-4', weights: [400, 600], italic: false },
];

let cssOut = '/* Auto-generated by scripts/vendor-copy.js — do not edit manually */\n\n';

for (const { pkg, weights, italic } of fonts) {
  const pkgDir = join(nm, pkg);
  const filesDir = join(pkgDir, 'files');
  // font name from package: @fontsource/dm-sans → dm-sans
  const fontSlug = pkg.split('/')[1];

  for (const w of weights) {
    // Normal weight
    const normalCssFile = join(pkgDir, `latin-${w}.css`);
    try {
      const css = readFileSync(normalCssFile, 'utf8');
      // Extract woff2 file references and copy them
      const woff2Matches = css.matchAll(/url\(\.\/files\/([\w-]+\.woff2)\)/g);
      let adjustedCss = css;
      for (const m of woff2Matches) {
        const filename = m[1];
        cpSync(join(filesDir, filename), join(fontsDir, filename));
        adjustedCss = adjustedCss.replace(`./files/${filename}`, `/fonts/${filename}`);
      }
      // Remove woff references (keep only woff2)
      adjustedCss = adjustedCss.replace(/,\s*url\([^)]*\.woff\)\s*format\(['"]woff['"]\)/g, '');
      cssOut += adjustedCss + '\n';
    } catch { /* weight not available */ }

    // Italic variant if needed
    if (italic && italic.includes(w)) {
      const italicCssFile = join(pkgDir, `latin-${w}-italic.css`);
      try {
        const css = readFileSync(italicCssFile, 'utf8');
        const woff2Matches = css.matchAll(/url\(\.\/files\/([\w-]+\.woff2)\)/g);
        let adjustedCss = css;
        for (const m of woff2Matches) {
          const filename = m[1];
          cpSync(join(filesDir, filename), join(fontsDir, filename));
          adjustedCss = adjustedCss.replace(`./files/${filename}`, `/fonts/${filename}`);
        }
        adjustedCss = adjustedCss.replace(/,\s*url\([^)]*\.woff\)\s*format\(['"]woff['"]\)/g, '');
        cssOut += adjustedCss + '\n';
      } catch { /* italic not available */ }
    }
  }

  console.log(`  fonts: ${fontSlug} (${weights.join(', ')})`);
}

writeFileSync(join(pub, 'fonts.css'), cssOut);
console.log('  → public/fonts.css written');
console.log('Done.');
